name: Build Backend Image

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout source
      uses: actions/checkout@v4


    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Build Image
      run: |
        IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}/backend" | tr '[:upper:]' '[:lower:]')
        
        docker build \
        -t $IMAGE_NAME:latest \
        ./backend


    - name: Push Image
      run: |
        IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}/backend" | tr '[:upper:]' '[:lower:]')

        docker push \
        $IMAGE_NAME:latest